---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bruce-registry-data
  name: knative-registry-data
  namespace: knative-build
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\me\OneDrive\system\bin\kompose.exe convert -f .\kubernetes-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: knative-registry
  name: knative-registry
  namespace: knative-build
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: knative-registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:443
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/cert.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/cert.key
        image: registry:2
        name: registry
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/registry
          name: knative-registry-data
        - mountPath: /certs
          name: certs
        ports:
        - containerPort: 443
      restartPolicy: Always
      volumes:
      - name: knative-registry-data
        persistentVolumeClaim:
          claimName: knative-registry-data
      - name: certs
        configMap:
          name:  knative-registry-certs

status: {}
# ---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: knative-registry-certs
#   namespace: knative-build
# data:
#   tls.crt:
#   tls.key:
# ---
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\me\OneDrive\system\bin\kompose.exe convert -f .\kubernetes-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: knative-registry
  name: knative-registry
  namespace: knative-build
spec:
  clusterIP: None
  ports:
  - name: knative-registry-http
    port: 443
    # nodePort: 80
    targetPort: 443
  selector:
    io.kompose.service: knative-registry
status:
  loadBalancer: {}
